module.exports = {
  arrayDiff: require('./algorithms/filters/function').arrayDiff,
  calculateHypotenuse: require('./algorithms/hypotenuse/function').calculateHypotenuse,
  factorial: require('./algorithms/factorial/function').factorial,
  filterType: require('./algorithms/filters/function').filterType,
  findAnagrams: require('./algorithms/anagrams/function').findAnagrams,
  findCount: require('./algorithms/search-and-match/function').findCount,
  gigasecond: require('./algorithms/gigasecond/function').gigasecond,
  generatePassword: require('./algorithms/password-generator/function').generatePassword,
  isAnagram: require('./algorithms/anagrams/function').isAnagram,
  isPalindrome: require('./algorithms/palindrome/function').isPalindrome,
  isPangram: require('./algorithms/pangram/function').isPangram,
  isPrime: require('./algorithms/prime-numbers/function').isPrime,
  isSquare: require('./algorithms/square-numbers/function').isSquare,
  lp100kmTompg: require('./algorithms/conversion/function').lp100kmTompg,
  mpgTolp100km: require('./algorithms/conversion/function').mpgTolp100km,
  queryParser: require('./algorithms/query-parser/function').queryParser,
  randBetween: require('./algorithms/randomize/function').randBetween,
  romanToArabic: require('./algorithms/roman-numerals/function').romanToArabic,
  search: require('./algorithms/search-and-match/function').search,
  shuffle: require('./algorithms/shuffle/function').shuffle,
  sortWord: require('./algorithms/anagrams/function').sortWord,
  sumMatrices: require('./algorithms/matrices/function').sumMatrices,
  transpose: require('./algorithms/transpose/function').transpose,
  wordCount: require('./algorithms/word-count/function').wordCount
};
